export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"首页\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"首页\",\"heroImage\":\"/logo.png\",\"heroText\":\"Halo-Theme-Hao\",\"tagline\":\"Halo-Theme-Hao 是一款适用于 Halo2.x 的博客主题，移植自 Hexo 社区中 张洪Heo 对 Hexo-Theme-Butterfly 主题的魔改版本\",\"actions\":[{\"text\":\"快速上手 💡\",\"link\":\"/tutorial/\",\"type\":\"primary\"},{\"text\":\"Docs\",\"link\":\"/tutorial/\"}],\"features\":[{\"title\":\"免费开源\",\"icon\":\"code\",\"details\":\"Hao 主题完全免费且开源，并由众多开发者参与研发与维护。\",\"link\":\"https://github.com/liuzhihang/halo-theme-hao\"},{\"title\":\"简单易用\",\"icon\":\"copy\",\"details\":\"在 GitHub 仓库中下载 Hao 主题，将其上传至 Halo 2.x 后台，即可使用。\",\"link\":\"https://docs.halo.run/user-guide/themes\"},{\"title\":\"设计精美\",\"icon\":\"palette\",\"details\":\"主题 UX/UI 由专业设计师 张洪Heo 设计研发，并在 Hexo 社区中广受好评。\",\"link\":\"https://blog.zhheo.com/\"},{\"title\":\"功能丰富\",\"icon\":\"mobile\",\"details\":\"得益于 Halo2.x 框架及其生态，主题中的众多功能配置简单，丰富齐全，即插即用，灵活优雅。\",\"link\":\"https://github.com/halo-sigs/awesome-halo\"},{\"title\":\"免费开源\",\"icon\":\"code\",\"details\":\"Hao 主题完全免费且开源，并由众多开发者参与研发与维护。\",\"link\":\"https://github.com/liuzhihang/halo-theme-hao\"},{\"title\":\"简单易用\",\"icon\":\"copy\",\"details\":\"在 GitHub 仓库中下载 Hao 主题，将其上传至 Halo 2.x 后台，即可使用。\",\"link\":\"https://docs.halo.run/user-guide/themes\"},{\"title\":\"设计精美\",\"icon\":\"palette\",\"details\":\"主题 UX/UI 由专业设计师 张洪Heo 设计研发，并在 Hexo 社区中广受好评。\",\"link\":\"https://blog.zhheo.com/\"},{\"title\":\"功能丰富\",\"icon\":\"mobile\",\"details\":\"得益于 Halo2.x 框架及其生态，主题中的众多功能配置简单，丰富齐全，即插即用，灵活优雅。\",\"link\":\"https://github.com/halo-sigs/awesome-halo\"}],\"copyright\":null,\"footer\":\"Theme by <a href=\\\"https://theme-hope.vuejs.press/\\\" target=\\\"_blank\\\">VuePress Theme Hope</a> | MIT Licensed, Copyright © 2022-present Mr.Hope\",\"description\":\"\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/Halo-Theme-Hao-Docs/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Halo-Theme-Hao\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"首页\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"首页\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.37,\"words\":412},\"filePathRelative\":\"README.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
