export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"Project home","i":"home","I":1},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"slides","I":1},["/slides","/slides.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","I":1},["/demo/disable","/demo/disable.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock","I":1},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown Enhance","i":"markdown","I":1},["/demo/markdown","/demo/markdown.md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"Page Config","i":"page","I":1},["/demo/page","/demo/page.md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"Features Demo","i":"discover","I":1},["/demo/index.html","/demo/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"Guide","i":"creative","I":1},["/guide/index.html","/guide/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"info","I":1},["/guide/bar/baz","/guide/bar/baz.md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar feature","i":"creative","I":1},["/guide/bar/index.html","/guide/bar/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"config","I":1},["/guide/foo/ray","/guide/foo/ray.md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo feature","i":"config","I":1},["/guide/foo/index.html","/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":"","I":1},["/404"]],
]
